REPORTER = dot

test:
   clear
   echo Starting test *********************************************************
   mocha \
   --reporter $(REPORTER) \
   $(MOCHA_OPTS) \
   *.js
   echo Ending test

test-w:
  @NODE_ENV=test mocha  test_syntaxhighlighter.js \
    --reporter $(REPORTER) \
    --growl \
    --watch

.PHONY: test test-w

