REPORTER = dot

test:
   clear
   echo Starting test *********************************************************
   ./node_modules/mocha/bin/mocha \
   --reporter $(REPORTER) \
   $(MOCHA_OPTS) \
   test/*.js
   echo Ending test

test-w:
  @NODE_ENV=test ./node_modules/.bin/mocha  test/syntaxhighlighter.test.js \
    --reporter $(REPORTER) \
    --growl \
    --watch

.PHONY: test test-w

